version: '3.5'

services:
  watchtower:
    image: v2tec/watchtower
    container_name: editor-watchtower
    restart: unless-stopped
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: --label-enable --cleanup --no-pull --interval 10

  localstack:
    image: localstack/localstack
    container_name: editor-localstack
    restart: unless-stopped
    environment:
      - SERVICES=s3,sqs
    volumes:
      - './tmp/localstack:/tmp/localstack'
      - './resources:/resources'
      - './test/test-files:/test/test-files'
      - './.localstack/startup:/docker-entrypoint-initaws.d'
      - './.localstack/config:/etc/localstackconf'
    ports:
      - 4566:4566
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost 4566'
      interval: 1m
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    container_name: editor-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' |  mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  editor-article-store:
    image: liberoadmin/editor-article-store:${TAG-latest}
    container_name: editor-article-store
    restart: unless-stopped
    depends_on:
      - mongo
      - localstack
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://root:password@editor-mongo:27017
      - MONGO_DB_NAME=editor
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_BUCKET_INPUT_EVENT_QUEUE_URL=http://editor-localstack:4566/000000000000/EditorImportQueue
      - AWS_END_POINT=http://editor-localstack:4566
      - AWS_SRC_BUCKET=s3-editor-source-bucket
      - AWS_EDITOR_BUCKET=s3-editor-destination-bucket
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  editor-client:
    image: liberoadmin/editor-client:${TAG-latest}
    container_name: editor-client
    restart: unless-stopped
    depends_on:
      - editor-article-store
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  editor-gateway:
    image: nginx:alpine
    container_name: editor-gateway
    depends_on:
      - editor-article-store
      - editor-client
    volumes:
      - "./src/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 3000:80

# Development Services
  editor-importer:
    build:
      context: './file-watcher'
    image: editor-importer:latest
    container_name: editor-importer
    depends_on:
      - localstack
    environment: 
      - S3_BUCKET=s3-editor-source-bucket
      - AWS_ENDPOINT=http://editor-localstack:4566
    volumes: 
      - "./tmp/s3-editor-source-bucket:/bucket-to-watch"